name: CI Bot Issue
on:
  issues:
    types:
      - opened

jobs:
  issue_opened:
    name: Issue Opened
    runs-on: ubuntu-latest
    steps:
      - uses: wzshiming/gh-ci-bot@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPOSITORY: ${{ github.repository }}
          LOGIN: ${{ github.event.issue.user.login }}
          MESSAGE: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_KIND: issue
          TYPE: created
          GREETING: |-
            Hi @${{ github.event.issue.user.login }},
            Thanks for opening an issue!
            We will look into it as soon as possible.
          DETAILS: |-

            <details>
            <summary>Details</summary>

            Instructions for interacting with me using comments are available [here](https://github.com/wzshiming/gh-ci-bot). you can see the result in [Workflow](https://github.com/${{ github.repository }}/actions?query=actor%3A${{ github.event.issue.user.login }}+workflow%3A\"CI+Bot+Comment\").
            If you have questions or suggestions related to my behavior, please file an issue against the [gh-ci-bot](https://github.com/wzshiming/gh-ci-bot) repository.

            </details>
